import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:logger/logger.dart';

// Initialize a logger for debugging
final _log = Logger();

/// Riverpod provider that returns a configured SupabaseClient.
///
/// It reads the Supabase URL, anon key and the MCP endpoint from the
/// `.env` file (generated by the user). The MCP endpoint is sent as a
/// custom HTTP header (`x-mcp-endpoint`) so that the request is proxied
/// through the Model Context Protocol gateway you supplied.
final supabaseProvider = Provider<SupabaseClient>((ref) {
  // Ensure .env is loaded – in most places (e.g., tests) we call
  // `await dotenv.load()` beforehand, but this guard makes the provider
  // safe to be used elsewhere as well.
  if (!dotenv.isInitialized) {
    try {
      dotenv.load(fileName: '.env');
    } catch (_) {}
  }

  final supabaseUrl = dotenv.env['SUPABASE_URL'] ?? 'https://placeholder.supabase.co';
  final supabaseAnonKey = dotenv.env['SUPABASE_ANON_KEY'] ?? 'placeholder';
  final mcpEndpoint = dotenv.env['MCP_SUPABASE_ENDPOINT'];
  if (mcpEndpoint == null) {
    _log.w('MCP endpoint not set – requests will go directly to Supabase');
  }

  // Create the client. The Supabase SDK does not expose a direct way to add a
  // custom header globally, so we use the `supabaseHeaders` map which is sent
  // with each request.
  final client = SupabaseClient(
    supabaseUrl,
    supabaseAnonKey,
    headers: mcpEndpoint != null ? {'x-mcp-endpoint': mcpEndpoint} : null,
  );
  if (mcpEndpoint != null) {
    _log.i('Supabase client configured to use MCP endpoint');
  }

  return client;
});
